ci:
  autofix_commit_msg: "chore(pre-commit): autofix run"
  autoupdate_commit_msg: "chore(pre-commit): autoupdate hooks"
  skip: [run-just-prepush]

default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/lmmx/just-pre-commit
    rev: v0.6.2
    hooks:
      - id: run-just-rust
        alias: run-just-precommit
        name: just (lints)
        args: ['precommit-ci']
        stages: [pre-commit]
      - id: run-just-rust
        alias: run-just-prepush
        name: just (tests)
        args: ['prepush']
        stages: [pre-push]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
      - id: name-tests-test
